# Generated by Django 5.0.3 on 2024-03-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsecundaria', '0003_registrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregar',
            fields=[
                ('vender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Appsecundaria.vender')),
            ],
            bases=('Appsecundaria.vender',),
        ),
    ]
