# Generated by Django 5.0.3 on 2024-03-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsecundaria', '0004_agregar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
