# Generated by Django 5.0.3 on 2024-03-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsecundaria', '0005_productoencarrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoencarrito',
            old_name='articulo',
            new_name='Articulo',
        ),
        migrations.RenameField(
            model_name='productoencarrito',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='productoencarrito',
            old_name='precio',
            new_name='Precio',
        ),
    ]
