# Generated by Django 5.0.3 on 2024-04-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsecundaria', '0007_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrar',
        ),
    ]
